services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'project-manager'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - '3306:3306'
    expose:
      - '3306'
